plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("kobweb-compose")
    id("com.varabyte.kobweb.internal.publish")
}

group = "com.varabyte.kobwebx"
version = libs.versions.kobweb.get()

kotlin {
    js {
        browser()
        compilerOptions.target = "es2015"
    }

    sourceSets {
        jsMain {
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.html.core)
                val faVersion = libs.versions.font.awesome.get()
                implementation(npm("@fortawesome/fontawesome-svg-core", faVersion))
                implementation(npm("@fortawesome/free-solid-svg-icons", faVersion))
                implementation(npm("@fortawesome/free-regular-svg-icons", faVersion))
                implementation(npm("@fortawesome/free-brands-svg-icons", faVersion))

                api(projects.frontend.kobwebCompose)
            }
        }
    }
}

val generateIcons by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/src/jsMain/kotlin")
    val srcFile = layout.projectDirectory.file("fa-icon-list.txt")
    val faVersion = libs.versions.font.awesome.get()
    inputs.property("faVersion", faVersion)
    inputs.file(srcFile)
    outputs.dir(outputDir)

    doLast {
        val lines = srcFile.asFile.readLines()

        check(lines.first() == "# Font Awesome $faVersion") {
            "Font Awesome version mismatch: Expected $faVersion but found ${lines.first().substringAfterLast(' ')}"
        }

        val categoryIcons = lines.dropWhile { it[0] == '#' }.map { line ->
            val (category, icons) = line.split('=')
            category to icons.split(',').map { icon ->
                "fa" + icon.split("-").joinToString("") { it.replaceFirstChar(Char::uppercase) }
            }
        }

        val iconsByCategory = categoryIcons.flatMap { (category, icons) ->
            icons.map { it to category }
        }.groupBy({ it.first }, { it.second })

        // Accessors for icon objects: https://docs.fontawesome.com/apis/javascript/import-icons
        val iconPropertiesCode = categoryIcons.joinToString(
            separator = "\n",
            prefix = """
                @file:Suppress("unused", "SpellCheckingInspection", "PackageDirectoryMismatch")
                    
                // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                // THIS FILE IS AUTOGENERATED.
                //
                // Do not edit this file by hand. Instead, update `fa-icon-list.txt` in the module root and run the Gradle
                // task "generateIcons"
                // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                package com.varabyte.kobweb.silk.internal.fa.svg
                """.trimIndent() + "\n\n",
        ) { (category, icons) ->
            icons.joinToString(
                separator = "\n",
                prefix = """
                    @JsModule("@fortawesome/free-$category-svg-icons")
                    internal external object Fa${category.replaceFirstChar(Char::uppercase)} {
                """.trimIndent() + "\n",
                postfix = "\n}",
            ) { name -> "\tval $name: dynamic" }
        }
        outputDir.get().file("FaIconProperties.kt").asFile.writeText(iconPropertiesCode)

        val composablesCode = iconsByCategory.toList().joinToString(
            separator = "\n",
            prefix = """ 
                //@formatter:off
                @file:Suppress("unused", "SpellCheckingInspection", "PackageDirectoryMismatch")
                
                // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                // THIS FILE IS AUTOGENERATED.
                //
                // Do not edit this file by hand. Instead, update `fa-icon-list.txt` in the module root and run the Gradle
                // task "generateIcons"
                // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                package com.varabyte.kobweb.silk.components.icons.fa
                
                import androidx.compose.runtime.*
                import com.varabyte.kobweb.compose.ui.Modifier
                import com.varabyte.kobweb.silk.internal.fa.svg.*
                """.trimIndent() + "\n\n",
        ) { (icon, categories) ->
            val methodName = icon.replaceFirstChar { it.uppercaseChar() }
            when {
                categories.size == 2 -> {
                    "@Composable fun $methodName(modifier: Modifier = Modifier, style: IconStyle = IconStyle.OUTLINE, size: IconSize? = null) = FaIcon(if (style == IconStyle.OUTLINE) FaRegular.$icon else FaSolid.$icon, modifier, size)"
                }

                else -> {
                    val holderClass = "Fa${categories.single().replaceFirstChar { it.uppercaseChar() }}"
                    "@Composable fun $methodName(modifier: Modifier = Modifier, size: IconSize? = null) = FaIcon($holderClass.$icon, modifier, size)"
                }
            }
        }

        outputDir.get().file("FaIcons.kt").asFile.writeText(composablesCode)
    }
}


kotlin {
    sourceSets.jsMain {
        kotlin.srcDir(generateIcons)
    }
}

kobwebPublication {
    artifactName.set("Kobweb Silk Icons (Font Awesome)")
    artifactId.set("silk-icons-fa-svg")
    description.set("A collection of composables that directly wrap Font Awesome icons.")
}
